package:
  name: pygments
  version: 2.1.3

source:
  fn: Pygments-2.1.3.tar.gz
  url: https://pypi.python.org/packages/source/P/Pygments/Pygments-2.1.3.tar.gz
  md5: ed3fba2467c8afcda4d317e4ef2c6150

build:
  entry_points:
    - pygmentize = pygments.cmdline:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - pygmentize -h
  imports:
    - pygments
    - pygments.lexers
    - pygments.formatters
    - pygments.styles
    - pygments.filters

about:
  home: http://pygments.org/
  license: BSD
  license_file: LICENSE
  summary: Pygments is a syntax highlighting package written in Python
