package:
  name: funcsigs
  version: 1.0.2

source:
  fn: funcsigs-1.0.2.tar.gz
  url: https://pypi.python.org/packages/94/4a/db842e7a0545de1cdb0439bb80e6e42dfe82aaeaadd4072f2263a4fbed23/funcsigs-1.0.2.tar.gz
  md5: 7e583285b1fb8a76305d6d68f4ccc14e

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - funcsigs

about:
  home: http://funcsigs.readthedocs.org/
  license: Apache
  license_file: LICENSE
  summary: Python function signatures from PEP362 for Python 2.6, 2.7 and 3.2+
  description: |
    Funcsigs is a backport of the PEP 362 function signature features from
    Python 3.3's inspect module. The backport is also compatible with Python
    2.6, 2.7, and 3.2 and up.
  doc_url: http://funcsigs.readthedocs.org/en/latest/
  dev_url: https://github.com/aliles/funcsigs
