# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/sockjs-tornado, last modified Thu Jun  2 23:00:22 2016
# ------------------------------------------------

package:
    name: sockjs-tornado
    version: 1.0.3
source:
    fn: sockjs-tornado-1.0.3.tar.gz
    md5: 4db7143a69cd8f9bbaf487ee93e1395c
    url: https://pypi.python.org/packages/63/4e/986818006b7177cfe3f8ee67145748740e3f81c134d6430a2dcd04d2a40d/sockjs-tornado-1.0.3.tar.gz
requirements:
    build:
        - python
        - setuptools
        - tornado >=2.1.1
    run:
        - python
        - tornado >=2.1.1
test:
    imports:
        - sockjs
        - sockjs.tornado
        - sockjs.tornado.transports
about:
    description: 'SockJS-tornado is a Python server side counterpart of SockJS-client

        browser library running on top of Tornado framework.

        '
    dev_url: https://github.com/mrjoes/sockjs-tornado/
    doc_url: https://pypi.python.org/pypi/sockjs-tornado
    home: http://github.com/mrjoes/sockjs-tornado/
    license: MIT
    license_file: LICENSE
    summary: SockJS python server implementation on top of Tornado framework
