# This file created by conda-build 2.0.8
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/pyzmq, last modified Tue Nov 22 16:33:25 2016
# ------------------------------------------------

package:
    name: pyzmq
    version: 16.0.2
source:
    fn: pyzmq-16.0.2.tar.gz
    md5: 9a8768b00a566a400d70318f8c359cfe
    url: https://pypi.python.org/packages/af/37/8e0bf3800823bc247c36715a52e924e8f8fd5d1432f04b44b8cd7a5d7e55/pyzmq-16.0.2.tar.gz
build: {}
requirements:
    build:
        - python
    run:
        - python
test:
    imports:
        - zmq
about:
    description: 'PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and
        fast

        messaging implementation.

        '
    dev_url: https://github.com/zeromq/pyzmq
    doc_url: https://pyzmq.readthedocs.org/en/latest/
    home: https://github.com/zeromq/pyzmq
    license: LGPL and BSD
    license_family: LGPL
    summary: zeromq bindings for Python
