# This file created by conda-build 2.0.8
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/jupyter_core, last modified Mon Dec  5 11:55:33 2016
# ------------------------------------------------

package:
    name: jupyter_core
    version: 4.2.1
source:
    fn: jupyter_core-4.2.1.tar.gz
    md5: f707f8693e537177341c4a89081fdac3
    url: https://pypi.python.org/packages/bc/d0/8f57f733913fbd4ce1a01991b008bace8dcf05158080821c6de76b4c5d01/jupyter_core-4.2.1.tar.gz
build:
    entry_points:
        - jupyter = jupyter_core.command:main
        - jupyter-migrate = jupyter_core.migrate:main
        - jupyter-troubleshoot = jupyter_core.troubleshoot:main
requirements:
    build:
        - python
    run:
        - python
        - traitlets
test:
    commands:
        - jupyter -h
        - jupyter-migrate -h
        - jupyter-troubleshoot -h
    imports:
        - jupyter_core
        - jupyter_core.utils
        - jupyter_core.tests
about:
    description: 'This package defines the core common functionality of Jupyter projects.

        '
    dev_url: https://github.com/jupyter/jupyter_core
    doc_url: http://jupyter-core.readthedocs.org/
    home: http://jupyter.org
    license: BSD
    summary: core Jupyter functionality
