# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/redis-py, last modified Sun Jun  5 21:47:39 2016
# ------------------------------------------------

package:
    name: redis-py
    version: 2.10.5
source:
    git_rev: 2.10.5
    git_url: https://github.com/andymccurdy/redis-py.git
requirements:
    build:
        - python
    run:
        - python
        - redis
about:
    description: 'The Python interface to the Redis key-value store. Requires a running

        Redis server.

        '
    dev_url: https://github.com/andymccurdy/redis-py/
    doc_url: https://pypi.python.org/pypi/redis
    home: https://github.com/andymccurdy/redis-py/
    license: MIT (https://github.com/andymccurdy/redis-py/blob/master/LICENSE)
    license_family: MIT
    license_file: LICENSE
    summary: Redis Python Client
