# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/heapdict, last modified Sat May 28 13:56:07 2016
# ------------------------------------------------

package:
    name: heapdict
    version: 1.0.0
source:
    fn: HeapDict-1.0.0.tar.gz
    md5: 47320e136156593c84072d09e770800f
    patches:
        - setup.patch
    url: https://pypi.python.org/packages/source/H/HeapDict/HeapDict-1.0.0.tar.gz
build:
    number: '1'
requirements:
    build:
        - python
    run:
        - python
test:
    imports:
        - heapdict
about:
    description: 'heapdict implements the MutableMapping ABC, meaning it works pretty
        much

        like a regular Python dict. It''s designed to be used as a priority queue.

        '
    dev_url: https://github.com/DanielStutzbach/heapdict
    doc_url: https://pypi.python.org/pypi/HeapDict
    home: http://stutzbachenterprises.com/
    license: BSD
    license_file: LICENSE
    summary: A heap with decrease-key and increase-key operations
