# This file created by conda-build 2.0.12
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/psutil, last modified Wed Dec 21 17:04:47 2016
# ------------------------------------------------

package:
    name: psutil
    version: 5.0.1
source:
    fn: psutil-5.0.1.tar.gz
    md5: 153dc8be94badc4072016ceeac7808dc
    url: https://pypi.python.org/packages/d9/c8/8c7a2ab8ec108ba9ab9a4762c5a0d67c283d41b13b5ce46be81fdcae3656/psutil-5.0.1.tar.gz
build:
    string: py27_0
requirements:
    build: !!python/object:__builtin__.instancemethod {}
    run:
        - python
test:
    imports:
        - psutil
        - psutil._psutil_posix
        - psutil._psutil_osx
about:
    description: 'psutil (process and system utilities) is a cross-platform library
        for

        retrieving information on running processes and system utilization (CPU,

        memory, disks, network) in Python. It is useful mainly for system

        monitoring, profiling and limiting process resources and management of

        running processes.

        '
    dev_url: https://github.com/giampaolo/psutil
    doc_url: http://pythonhosted.org/psutil/
    home: https://github.com/giampaolo/psutil
    license: BSD
    license_file: LICENSE
    summary: A cross-platform process and system utilities module for Python
