# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /Users/ilan/anaconda/packages/terminado, last modified Thu Jun  2 15:46:07 2016
# ------------------------------------------------

package:
    name: terminado
    version: '0.6'
source:
    fn: terminado-0.6.tar.gz
    md5: 5b6c65da27fe1ed07a9f80f0588cdaba
    url: https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz
requirements:
    build:
        - python
    run:
        - python
        - tornado >=4.0
        - ptyprocess
test:
    imports:
        - terminado
about:
    description: 'Terminado is a Tornado websocket backend for the term.js Javascript

        terminal emulator library.

        '
    dev_url: https://github.com/takluyver/terminado
    doc_url: http://terminado.readthedocs.org/en/latest/
    home: https://github.com/takluyver/terminado
    license: BSD
    summary: Terminals served to term.js using Tornado websockets
